blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/release-health/react-native-release-health/discussions
    about: For usage questions and open-ended discussion.
